# Generated by Django 4.0 on 2022-02-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('text', models.TextField()),
            ],
        ),
    ]
